before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
build:
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.intes.by/dimao/pyticket.git
    - docker build --pull -t "$CI_REGISTRY_IMAGE":dev .
    - docker push "$CI_REGISTRY_IMAGE"
test:
  script:
    - docker-compose -f docker-compose-dev.yml run --rm
