---
stages:
  - build
  - test
before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker-compose --version
build_image:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":dev .
    - docker push "$CI_REGISTRY_IMAGE"
pytest:
  stage: test
  script:
    - docker-compose -f docker-compose-dev.yml run python-tests
