version: '2'
services:
  ftp_sync:
    container_name: ftp-sync
    image: registry.intes.by/dimao/ftp-sync:master
    environment:
      - USER=
      - PASSWORD=
      - SERVER=
      - CHECK_INTERVAL=5
    volumes:
      - /intes/import-ticket/tickets:/tickets
    restart: always

  pyticket:
    image: registry.intes.by/dimao/pyticket:master
    container_name: import-ticket
    hostname: import-ticket
    volumes:
      - ./config.json/:/config.json
      - /intes/import-ticket/tickets:/tickets
      - /var/run/docker.sock:/docker.sock
    ports:
      - "9090:9090"
    depends_on:
      - ftp_sync
    restart: always

  python-tests:
    image: registry.intes.by/dimao/pyticket:master
    volumes:
      - ./config.json/:/config.json
    entrypoint: python3 -m pytest tests