version: '2'
services:
  ftp_sync:
    container_name: ftp-sync
    image: registry.intes.by/dimao/ftp-sync:master
    environment:
      - USER=${user}
      - PASSWORD=${password}
      - SERVER=
      - CHECK_INTERVAL=5
    volumes:
      - /intes/import-ticket/tickets:/tickets
    restart: always

  pyticket:
    image: registry.intes.by/dimao/pyticket:master
    volumes:
      - ./config.json/:/config.json
      - /intes/import-ticket/tickets:/tickets
    ports:
      - "9090:9090"
    entrypoint: python3 -m pytest tests
    depends_on:
      - ftp_sync
    restart: always

  python-tests:
    image: registry.intes.by/dimao/pyticket:master
    volumes:
      - ./config.json/:/config.json
    entrypoint: python3 -m pytest tests